Repository bu-ist/responsive-framework, pull requests merged in 2018-12, with the labels that each got.

#127 Remove bundle install from gruntfile
  CHANGELOG.md
  package.json
Labels: Build Tools/Tests, 🎉 enhancement

#129 Feature/text widget button
  CHANGELOG.md
  README.md
  ie.css
  ie.css.map
  ie.min.css
  ie.min.css.map
  inc/customizer.php
  languages/responsive-framework.pot
  package-lock.json
  style.css
  style.css.map
  style.min.css
  style.min.css.map
Labels: 🔥 bug

#133 Feature/print styles
  CHANGELOG.md
  footer.php
  functions.php
  ie.css
  ie.css.map
  ie.min.css
  ie.min.css.map
  inc/customizer.php
  style.css
  style.css.map
  style.min.css
  style.min.css.map
Labels: 🎉 enhancement
