Repository bu-ist/responsive-framework, pull requests merged in 2019-03, with the labels that each got.

#157 Set bu_banner_has_text to true on front-end only
  inc/bu-banners.php
Labels: 🔥 bug

#156 Feature/autoprefixer
  CHANGELOG.md
  Gruntfile.js
  admin/admin.css
  admin/admin.css.map
  languages/responsive-framework.pot
  package-lock.json
  package.json
  style.css
  style.css.map
  style.min.css
  style.min.css.map
Labels: 🎉 enhancement

#155 Feature/bu navigation primarynav bugfix
  CHANGELOG.md
  inc/bu-template-tags.php
Labels: 🔥 bug

#158 Feature/fix responsive get posts archive link notices
  CHANGELOG.md
  inc/template-tags.php
Labels: 🔥 bug

#140 Improve edit link user interface
  CHANGELOG.md
  page-templates/news.php
  page-templates/no-sidebars.php
  page.php
  profiles.php
  single-profile.php
  single.php
  template-parts/content.php
  template-parts/news.php
  template-parts/profile-advanced.php
  template-parts/profile-basic.php
  template-parts/profile-mini.php
  template-parts/profile.php
Labels: 🚀 ready for release

#150 Color palette enhancements
  Gruntfile.js
  admin/admin.css
  admin/admin.css.map
  admin/theme-customizer.php
  css-dev/admin.scss
  css-dev/customizer/color-palettes/_complimentary.scss
  css-dev/customizer/color-palettes/_monochromatic.scss
  css-dev/customizer/color-palettes/_palettes.scss
  css-dev/customizer/color-palettes/_styles-base.scss
  css-dev/customizer/color-palettes/_styles-content.scss
  css-dev/customizer/color-palettes/_styles-footer.scss
  css-dev/customizer/color-palettes/_styles-navigation.scss
  css-dev/customizer/color-palettes/_styles-sidebar.scss
  css-dev/customizer/color-palettes/_triad.scss
  css-dev/customizer/color-palettes/comm_ave.scss
  css-dev/customizer/color-palettes/default.scss
  css-dev/customizer/color-palettes/eiffel.scss
  css-dev/customizer/color-palettes/extra-spectral.scss
  css-dev/customizer/color-palettes/rayleigh-scattering.scss
  css-dev/customizer/color-palettes/slacker.scss
  css-dev/customizer/color-palettes/vinca-minor.scss
  css-dev/customizer/font-palettes/_palettes.scss
  css-dev/customizer/font-palettes/fonts/_shared.scss
  css/comm_ave.css
  css/default.css
  css/eiffel.css
  css/extra-spectral.css
  css/f1.css
  css/f2.css
  css/f3.css
  css/f4.css
  css/f5.css
  css/rayleigh-scattering.css
  css/slacker.css
  css/vinca-minor.css
  inc/customizer.php
  js/vendor/lightgallery/css/lg-fb-comment-box.css
  js/vendor/lightgallery/css/lg-transitions.css
  js/vendor/lightgallery/css/lightgallery.css
  languages/responsive-framework.pot
  package-lock.json
  tests/test-customizer.php
Labels: 🚀 ready for release

#162 Hotfix/font color upgrade
  CHANGELOG.md
  css-dev/style.scss
  functions.php
  ie.css
  ie.min.css
  ie.min.css.map
  inc/upgrade.php
  languages/responsive-framework.pot
  style.css
  style.css.map
  style.min.css
  style.min.css.map
Labels: 🔥 bug

#109 Migrate Open PR #393 from 1x-develop Inconsistent Sidebar Behavior
  CHANGELOG.md
  admin/theme-customizer.php
  functions.php
  inc/customizer.php
  inc/upgrade.php
  tests/test-narrow-template-constants.php
Labels: Needs Feedback, Target Next Release, Testing in progress, 🔥 bug
